name: Build and Test

on:
  push:
    branches:
      - master
      - main
  pull_request: # all
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      
    - name: Concurrency
      run: go vet -c 5 ./...

    - name: Test
      run: go test -v ./...
